<a href="https://colab.research.google.com/github/ShashankDsa/Task-6/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Aim
### **To implement a linear regression with regularization via gradient descent. to implement gradient descent with Lp norm, for 3 different values of p in (1,2]**

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/sample_data/Boston.csv")
df.head()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
df.isnull().sum()

Unnamed: 0    0
crim          0
zn            0
indus         0
chas          0
nox           0
rm            0
age           0
dis           0
rad           0
tax           0
ptratio       0
black         0
lstat         0
medv          0
dtype: int64

In [5]:
df.corr()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
Unnamed: 0,1.000000,0.407407,-0.103393,0.399439,-0.003759,0.398736,-0.079971,0.203784,-0.302211,0.686002,0.666626,0.291074,-0.295041,0.258465,-0.226604
crim,0.407407,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
zn,-0.103393,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
indus,0.399439,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
chas,-0.003759,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
nox,0.398736,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
rm,-0.079971,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
age,0.203784,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
dis,-0.302211,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
rad,0.686002,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
tax,0.666626,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
ptratio,0.291074,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
black,-0.295041,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
lstat,0.258465,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
medv,-0.226604,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [55]:
X = df[["crim","zn","indus","nox","rm","age","dis","rad","tax","ptratio","black","lstat"]]
y = df["medv"]

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

### Linear Regression

In [56]:
from sklearn.linear_model import LinearRegression #importing all the required functions
regressor = LinearRegression()
"Syntax : varName = ModelName(modelHyperParams)"
regressor.fit(X_train, y_train)

LinearRegression()

In [57]:
y_pred = regressor.predict(X_test) # given the features of the test dataset, it will give the final predictions
"Syntax : varName.predict(test_features)"
y_pred

array([23.52916544, 21.21658702, 17.83178275, 18.51196583, 19.14843981,
       14.98247706, 22.75205475, 22.73585275, 13.92874012, 16.65712649,
       27.66568798, 23.26437722, 25.78221964, 16.03707303, 19.50134005,
       19.42643454, 23.73865969, 21.03069591, 25.83714573, 22.21179097,
       38.66211643, 25.26701098,  8.93012069, 29.59085892, 28.65822125,
       25.07546419, 28.25992127, 14.77741028, 22.65600767, 20.6343538 ,
       27.47806033, 18.43385715, 32.74785597, 16.14826064, 39.94894606,
       27.21435955, 14.05685285, 17.16576236, 25.8385673 , 16.1181627 ,
       25.35259878, 30.09116823,  8.03260775, 28.96933311,  9.33390916,
       21.16086995, 27.68864516, 27.7374305 , 32.02174855, 17.74201498,
       20.36808484, 25.79539749, 23.01856931, 17.79470205, 38.19353626,
       13.53232425, 15.90346983, 13.17629265, 26.70076537, 11.78908344,
       28.47514153, 14.6736441 , 23.50277091, 23.7778975 ,  9.39525979,
       17.2083348 , 14.58171673, 32.8497397 , 32.65991917, 13.78989137,
       13.2745228 , 21.33031747, 13.72119935, 18.76288703, 36.12312359,
       38.17247025,  7.39227117, 34.87948168, 33.08897197, 17.57592582,
       18.27753836, 20.63677304, 12.65873314, 19.73673837, 23.00730001,
       23.25131024, 20.48295816, 31.80918627, 25.16953334, 29.49755021,
       14.60054142, 12.51584183, 23.20022803, 20.57211506, 22.61992598,
       25.60478749, 20.87535604, 15.52021755,  3.50329807, 16.88634701,
       14.14319996,  7.48132307, 18.61111921, 34.69122789, 23.04427535,
       21.40324786, 37.12987491, 18.38358477, 25.30015909, 30.0929347 ,
       18.69570014, 22.4716151 , 22.55278903, 27.38409286, 15.9897627 ,
       14.28164059, 14.3931739 , 21.38302886, 24.01668265, 19.35147504,
       20.16928352, 36.56029177, 33.35899327, 33.55640845, 14.28677296,
       39.37593938, 18.59263513])

In [58]:
df1 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1.head()

     Actual  Predicted
116    21.2  23.529165
330    19.8  21.216587
60     18.7  17.831783
376    13.9  18.511966
381    10.9  19.148440

In [59]:
from sklearn import metrics 
print('R2- SCORE:', metrics.r2_score(y_test,y_pred))

R2- SCORE: 0.732606170799987

### **Lasso Regression**

In [60]:
from sklearn.linear_model import Lasso

In [61]:
Lasso_Reg = Lasso() 
"Syntax : varName = ModelName(modelHyperParams)"
Lasso_Reg.fit(X_train, y_train)

Lasso()

In [62]:
y_pred1 = Lasso_Reg.predict(X_test)
"Syntax : varName.predict(test_features)"
y_pred1

array([22.96571343, 21.62170844, 20.87566052, 14.8626322 , 16.56866515,
       16.43277901, 25.51614012, 25.48843369, 12.15335877, 14.18370861,
       28.00422322, 24.84411468, 26.19048783, 18.77873986, 20.51763958,
       22.75692547, 24.26201268, 20.41366704, 25.2228205 , 25.65299073,
       34.24362491, 27.40757848, 12.33573845, 29.25127816, 30.90361492,
       26.15974134, 27.58340347, 14.36509626, 23.62506857, 20.82938893,
       26.9442481 , 24.43015725, 29.3317378 , 16.60258488, 37.35524801,
       28.38345211,  9.8995127 , 19.05225526, 25.97168035, 15.2060286 ,
       24.38406005, 27.3506396 ,  7.25512451, 29.75825944,  8.51446362,
       20.59854178, 27.02140945, 27.53284346, 30.08292655, 17.24452245,
       21.59189596, 27.09446178, 24.04710533, 21.20587318, 34.23828578,
       16.4528934 , 17.93893151, 15.36794771, 27.57762009, 12.88738682,
       27.33715637, 12.91566357, 24.97162567, 24.11507579,  8.52685396,
       18.76276314, 16.41043746, 30.23738379, 31.7361571 , 13.89699169,
       14.29708724, 22.25704157, 23.6010424 , 18.60490852, 31.83319821,
       35.79976165, 10.20773551, 34.18221489, 31.27623801, 13.53957893,
       19.17771899, 23.18072672, 15.29625289, 17.93705084, 23.19593322,
       23.78894984, 20.53203392, 31.36572588, 25.78582962, 28.47627561,
       14.99553467, 11.0144926 , 23.67890272, 22.06619431, 20.31575814,
       24.8898756 , 21.16367363, 16.88945194,  2.40459066, 15.63334963,
       14.43592359,  8.0757236 , 21.50835674, 33.01954259, 20.02144968,
       21.28982703, 34.97138314, 16.95815577, 26.27773608, 29.35114017,
       20.15045593, 24.7645415 , 23.65692563, 27.97078222, 17.98655833,
       16.95645186, 15.80346119, 21.59446088, 23.48236566, 18.34445731,
       19.38837571, 34.90883185, 34.36767584, 30.16958509, 15.13937056,
       35.45208803, 19.8002221 ])

In [63]:
df2 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred1})
df2.head()

     Actual  Predicted
116    21.2  22.965713
330    19.8  21.621708
60     18.7  20.875661
376    13.9  14.862632
381    10.9  16.568665

In [64]:
from sklearn import metrics 
print('R2- SCORE:', metrics.r2_score(y_test,y_pred1))

R2- SCORE: 0.7015535023156987

### **Ridge Regression**

In [65]:
from sklearn.linear_model import Ridge
Ridge_Reg = Ridge()
Ridge_Reg.fit(X_train, y_train)

Ridge()

In [66]:
y_pred2 = Ridge_Reg.predict(X_test)
"Syntax : varName.predict(test_features)"
y_pred2

array([23.3547052 , 21.21345002, 17.84390953, 18.43469095, 19.09026009,
       15.17223715, 23.13768319, 23.7312056 , 14.35341568, 16.61842003,
       27.85974571, 23.29351032, 25.79365161, 16.18488331, 19.74577996,
       19.94837355, 23.51312593, 21.12659935, 25.34343399, 23.04635404,
       38.60970905, 25.48866786, 10.22078701, 29.24182619, 29.22408543,
       25.22795647, 28.51679684, 14.11230424, 22.6239481 , 20.47538255,
       27.38590005, 19.89438788, 32.46718337, 16.65704526, 40.24697446,
       27.39293727, 13.92582499, 17.44376518, 25.87805479, 16.41520218,
       25.12798469, 30.61188433,  7.28003168, 28.77796697,  8.61303838,
       20.95118287, 27.51855081, 27.59818356, 31.90578465, 18.27874497,
       20.48362853, 25.8082883 , 22.94143191, 19.30792548, 37.93936341,
       13.73989263, 16.09138892, 12.9039931 , 27.04980487, 11.86563215,
       27.98579021, 14.68795041, 23.50779911, 23.28947479,  9.69486974,
       16.9280526 , 14.65365861, 32.40314761, 32.64174074, 13.86337961,
       13.85745659, 21.1581041 , 14.1303711 , 18.45935305, 36.35061834,
       37.88508564,  7.63759945, 35.11303005, 33.031166  , 16.77345932,
       18.47901173, 20.70369374, 13.97882667, 19.8458709 , 23.04524857,
       22.92807393, 20.72904163, 31.63752001, 24.91696772, 28.9571733 ,
       13.92499063, 12.8821031 , 22.76511148, 20.36285487, 22.15729884,
       25.59905781, 20.72406034, 15.49817581,  2.67269927, 17.13556883,
       14.14522054,  7.4324239 , 18.95928758, 34.49076166, 23.44021117,
       20.96067587, 36.78580065, 18.49388113, 25.50308136, 29.82283696,
       18.88529444, 23.09066177, 23.10046989, 27.46279128, 16.07622417,
       14.36585352, 14.39184706, 20.91388466, 24.07457257, 19.74621486,
       19.95141869, 36.98606954, 33.34484359, 33.5303162 , 14.44765903,
       38.95340499, 18.65921568])

In [67]:
df3 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred2})
df3.head()

     Actual  Predicted
116    21.2  23.354705
330    19.8  21.213450
60     18.7  17.843910
376    13.9  18.434691
381    10.9  19.090260

In [68]:
from sklearn import metrics 
print('R2- SCORE:', metrics.r2_score(y_test,y_pred2))

R2- SCORE: 0.7310696132460238

### **CROSS-VALIDATION**

In [69]:
from sklearn.model_selection import cross_validate
regressor = LinearRegression(normalize = True) #untrained model

In [70]:
cv_results = cross_validate(regressor, X, y, cv=10, scoring = "r2")
cv_results['test_score'].mean()

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,

0.22111057606345358